### ISSUE TITLE
How to obtain Token 

### ISSUE THREAD

**Issue by biniamHaddish** [voysis/voysis-android#12]
how can i obtain Token and and what is the URL in order to make this app work?

**Comment by johnfitzpat** [comment]
Hi Biniam, the Voysis platform and the Voysis Commerce product allows any brand to have their own brand-specific voice experience right within their apps and websites. To do this, we create an AI that is custom to each of our customers. Unlike generic Voice AI services, Voysis services are trained to understand the intricacies of your products and services. You can learn more about Voysis Commerce and how to get your own AI here: https://voysis.com/commerce/
